/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-17 05:02:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import co.kh.dev.common.MyUtility;
import co.kh.dev.home.model.CustomerVO;
import java.util.ArrayList;
import co.kh.dev.home.model.CustomerVO;
import co.kh.dev.home.model.CustomerDAO;
import co.kh.dev.common.MyUtility;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/home/carouselSection.jsp", Long.valueOf(1733907750091L));
    _jspx_dependants.put("/home/footer.jsp", Long.valueOf(1733897706878L));
    _jspx_dependants.put("/home/headerNav.jsp", Long.valueOf(1734066927819L));
    _jspx_dependants.put("/home/loginSection.jsp", Long.valueOf(1734411715346L));
    _jspx_dependants.put("/home/css/commonCss.jsp", Long.valueOf(1734337424577L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("co.kh.dev.common.MyUtility");
    _jspx_imports_classes.add("co.kh.dev.home.model.CustomerVO");
    _jspx_imports_classes.add("co.kh.dev.home.model.CustomerDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String msg=(String)request.getAttribute("msg");
boolean alertFlag=(msg==null||msg.equals(""))?false:true;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>메인 화면</title>\r\n");
      out.write("	<script src=\"https://kit.fontawesome.com/6ff644124c.js\"	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/carouselSection.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/headerNav.css\" />");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/MainPage.css\" />\r\n");

if(alertFlag){

      out.write("	\r\n");
      out.write("<script>\r\n");
      out.write("alert(\"");
      out.print(msg);
      out.write("\"); \r\n");
      out.write("window.location.replace(\"");
      out.print(request.getContextPath());
      out.write("/home/mainPage.jsp\");\r\n");
      out.write("</script>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write(" <nav class=\"headerNav\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"headerNav\">\r\n");
      out.write("      <i class=\"fa-solid fa-cat\" onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/home/mainPage.jsp'\"></i>\r\n");
      out.write("	<ul class=\"mainMenu\">\r\n");
      out.write("		<li data-menu=\"one\">Item One</li>\r\n");
      out.write("		<li data-menu=\"two\">Item Two</li>\r\n");
      out.write("		<li data-menu=\"three\">Item Three</li>\r\n");
      out.write("		<li data-menu=\"four\">고객 지원</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	");

  CustomerVO cvo2 = MyUtility.returnCvoBySession(session);
  if(cvo2==null){
  
      out.write("\r\n");
      out.write("	<button class=\"Button\" class=\"authButton\" onClick=\"openLoginPopup();\">로그인</button>\r\n");
      out.write("	");

  } else{
  
      out.write("\r\n");
      out.write("	<button class=\"Button\" class=\"authButton\" onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/home/logout.jsp'\">로그아웃</button>\r\n");
      out.write("	");

  }
  
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"subMenuContainer\">\r\n");
      out.write("	<ul class=\"subMenu\" data-submenu=\"one\">\r\n");
      out.write("		<li><a href=\"#\">Submenu 1</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu 2</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu 3</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<ul class=\"subMenu\" data-submenu=\"two\">\r\n");
      out.write("		<li><a href=\"#\">Submenu A</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu B</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu C</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<ul class=\"subMenu\" data-submenu=\"three\">\r\n");
      out.write("		<li><a href=\"#\">Submenu X</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu Y</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu Z</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<ul class=\"subMenu\" data-submenu=\"four\">\r\n");
      out.write("		<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/home/boardPage.jsp\">게시판</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu Beta</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu Gamma</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/home/js/headerNav.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/home/js/common.js\"></script>");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write(" <section class=\"carouselSection\">\r\n");
      out.write("    <div class=\"carousel\">\r\n");
      out.write("      <div id=\"slide_show\">\r\n");
      out.write("        <a href=\"#\"\r\n");
      out.write("          ><img src=\"./media/slide-1.jpg\" alt=\"\" class=\"slide\" id=\"p1\"\r\n");
      out.write("        /></a>\r\n");
      out.write("        <a href=\"#\"\r\n");
      out.write("          ><img src=\"./media/slide-2.jpg\" alt=\"\" class=\"slide\" id=\"p2\"\r\n");
      out.write("        /></a>\r\n");
      out.write("        <a href=\"#\"\r\n");
      out.write("          ><img src=\"./media/slide-3.jpg\" alt=\"\" class=\"slide\" id=\"p3\"\r\n");
      out.write("        /></a>\r\n");
      out.write("        <a href=\"#\"\r\n");
      out.write("          ><img src=\"./media/slide-4.jpg\" alt=\"\" class=\"slide\" id=\"p4\" />\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <i class=\"fa-solid fa-circle-chevron-left\" id=\"navgateleft\"></i>\r\n");
      out.write("      <i class=\"fa-solid fa-circle-chevron-right\" id=\"navgateright\"></i>\r\n");
      out.write("      <div id=\"indicator\">\r\n");
      out.write("        <a href=\"#\" class=\"active\">\r\n");
      out.write("          <i class=\"fa-solid fa-circle-dot\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\"> <i class=\"fa-solid fa-circle-dot\"></i></a\r\n");
      out.write("        ><a href=\"#\"> <i class=\"fa-solid fa-circle-dot\"></i></a\r\n");
      out.write("        ><a href=\"#\"> <i class=\"fa-solid fa-circle-dot\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/home/js/carousel.js\"></script>\r\n");
      out.write("	  \r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("</header>\r\n");
      out.write("    <main class=\"mainPage\">\r\n");
      out.write("        <section class=\"sideSection\">Side Menu</section>\r\n");
      out.write("        <section class=\"mainSection\">\r\n");
      out.write("            <!-- 게시판 요약 정보 -->\r\n");
      out.write("            <article class=\"boardArticle\">\r\n");
      out.write("                <h3>게시판 요약</h3>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>번호</th>\r\n");
      out.write("                            <th>제목</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>1</td>\r\n");
      out.write("                            <td>게시판 테스트 제목</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>2</td>\r\n");
      out.write("                            <td>다른 게시판 제목</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </article>\r\n");
      out.write("            <!-- 상품 요약 정보 -->\r\n");
      out.write("            <article class=\"productArticle\">\r\n");
      out.write("                <h3>상품 요약</h3>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>상품명</th>\r\n");
      out.write("                            <th>가격</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>상품 1</td>\r\n");
      out.write("                            <td>10,000원</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>상품 2</td>\r\n");
      out.write("                            <td>20,000원</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </article>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"loginSection\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

CustomerVO cvo = MyUtility.returnCvoBySession(session);
Cookie[] ckList= request.getCookies();
String cid = null;
    for (Cookie cookie : ckList) {
        // 원하는 쿠키 이름 확인
        if (cookie.getName().equals("id")) {  
             cid= cookie.getValue();  // 쿠키 값 가져오기
        }
    }

      out.write("\r\n");
      out.write("\r\n");

if (cvo == null) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<article class=\"loginInput\">\r\n");
      out.write("	<form method=\"post\" action=\"/jspHomePage/BoardLoginCheckServlet.do\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><input type=\"text\" name=\"id\" id=\"id\"\r\n");
      out.write("				placeholder=\" 아이디 또는 전화번호\" ");
      out.print((!MyUtility.isNullOrEmpty(cid))?"value="+cid:"" );
      out.write("></li>\r\n");
      out.write("			<li><input type=\"password\" name=\"pwd\" id=\"psw\"\r\n");
      out.write("				placeholder=\" 비밀번호\" /></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<!-- 상태유지 -->\r\n");
      out.write("		<div class=\"maint\">\r\n");
      out.write("			<input type=\"checkbox\" name=\"maint\" class=\"maint\" ");
      out.print((!MyUtility.isNullOrEmpty(cid))?"checked":"" );
      out.write("> <label\r\n");
      out.write("				for=\"maint\" >아이디 저장</label>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 로그인 버튼 -->\r\n");
      out.write("		<button type=\"submit\">로그인</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"loginNav\">\r\n");
      out.write("	<ul style=\"display: flex\">\r\n");
      out.write("		<li><a href=\"#\">비밀번호 찾기</a></li>\r\n");
      out.write("		<li><a href=\"#\">아이디 찾기</a></li>\r\n");
      out.write("		<li><a href=\"registPage.jsp\">회원가입</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

} else {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 성공 화면 -->\r\n");
      out.write("<table class=\"afterLoginPage\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"300\" align=\"center\">");
      out.print(cvo.getName());
      out.write(" 님 로그인 되었습니다.</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<nav class=\"loginNav\">\r\n");
      out.write("	<ul style=\"display: flex\">\r\n");
      out.write("		<li><a href=\"myPage.jsp\">마이페이지</a></li>\r\n");
      out.write("		<li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("        <hr>\r\n");
      out.write("    <footer>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("      <article>\r\n");
      out.write("        <div><a href=\"#\">로그인 | </a><a href=\"#\">전체서비스 | </a><a href=\"#\">서비스안내 | </a><a href=\"#\">오류신고 | </a><a href=\"#\">고객센터 | </a></div>\r\n");
      out.write("        <div>직접 콘텐츠를 편집합니다.</div>\r\n");
      out.write("        <div>이 콘텐츠의 저작권은 저작권자 또는 제공처에 있으며, 이를 무단 이용하는 경우 저작권법 등에 따라 법적 책임을 질 수 있습니다.</div>\r\n");
      out.write("      </article>");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
