/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-19 09:14:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import co.kh.dev.common.MyUtility;
import co.kh.dev.home.model.CustomerVO;
import co.kh.dev.home.model.CommentVO;
import co.kh.dev.common.MyUtility;
import co.kh.dev.home.model.BoardVO;
import java.util.ArrayList;
import co.kh.dev.home.model.CustomerVO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import co.kh.dev.home.model.CustomerVO;
import co.kh.dev.home.model.CustomerDAO;
import co.kh.dev.common.MyUtility;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/home/sideSection.jsp", Long.valueOf(1734592922717L));
    _jspx_dependants.put("/home/footerSection.jsp", Long.valueOf(1733897706878L));
    _jspx_dependants.put("/home/headerNavSection.jsp", Long.valueOf(1734593880680L));
    _jspx_dependants.put("/home/carouselSection.jsp", Long.valueOf(1734590411861L));
    _jspx_dependants.put("/home/loginSection.jsp", Long.valueOf(1734599304675L));
    _jspx_dependants.put("/home/css/commonCss.jsp", Long.valueOf(1734337424577L));
    _jspx_dependants.put("/home/miniBoardSection.jsp", Long.valueOf(1734590567995L));
    _jspx_dependants.put("/home/miniShoppingSection.jsp", Long.valueOf(1734588100836L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("co.kh.dev.common.MyUtility");
    _jspx_imports_classes.add("co.kh.dev.home.model.CustomerVO");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("co.kh.dev.home.model.CommentVO");
    _jspx_imports_classes.add("co.kh.dev.home.model.BoardVO");
    _jspx_imports_classes.add("co.kh.dev.home.model.CustomerDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

/* if (request.getAttribute("bList") == null) {
	response.sendRedirect(request.getContextPath() + "/mainPageAlert.do");
} */
String msg = (String) request.getAttribute("msg");
boolean alertFlag = (boolean) request.getAttribute("alertFlag");
System.out.print((String) request.getAttribute("msg"));
System.out.print((boolean) request.getAttribute("alertFlag"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>메인 화면</title>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/6ff644124c.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/carouselSection.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/headerNav.css\" />");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/MainPage.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/miniBoardSection.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/sideSection.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/home/css/miniShoppingSection.css\" />\r\n");

if (alertFlag) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("alert(\"");
      out.print(msg);
      out.write("\"); \r\n");
      out.write("window.location.replace(\"");
      out.print(request.getContextPath());
      out.write("/mainPageAlert.do\");\r\n");
      out.write("</script>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav class=\"headerNav\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"headerNav\">\r\n");
      out.write("      <i class=\"fa-solid fa-cat\" onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/mainPageAlert.do'\"></i>\r\n");
      out.write("	<ul class=\"mainMenu\">\r\n");
      out.write("		<li data-menu=\"one\">Item One</li>\r\n");
      out.write("		<li data-menu=\"two\">Item Two</li>\r\n");
      out.write("		<li data-menu=\"three\">Item Three</li>\r\n");
      out.write("		<li data-menu=\"four\">고객 지원</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	");

  CustomerVO cvo2 = MyUtility.returnCvoBySession(session);
  if(cvo2==null){
  
      out.write("\r\n");
      out.write("	<button class=\"Button\" class=\"authButton\" onClick=\"openLoginPopup();\">로그인</button>\r\n");
      out.write("	");

  } else{
  
      out.write("\r\n");
      out.write("	<button class=\"Button\" class=\"authButton\" onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/home/customerLogout.do'\">로그아웃</button>\r\n");
      out.write("	");

  }
  
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"subMenuContainer\">\r\n");
      out.write("	<ul class=\"subMenu\" data-submenu=\"one\">\r\n");
      out.write("		<li><a href=\"#\">Submenu 1</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu 2</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu 3</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<ul class=\"subMenu\" data-submenu=\"two\">\r\n");
      out.write("		<li><a href=\"#\">Submenu A</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu B</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu C</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<ul class=\"subMenu\" data-submenu=\"three\">\r\n");
      out.write("		<li><a href=\"#\">Submenu X</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu Y</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu Z</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<ul class=\"subMenu\" data-submenu=\"four\">\r\n");
      out.write("		<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/boardSelect.do\">게시판</a></li>\r\n");
      out.write("		<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/noticeSelect.do\">공지사항</a></li>\r\n");
      out.write("		<li><a href=\"#\">Submenu Gamma</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/home/js/headerNav.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/home/js/common.js\"></script>");
      out.write("\r\n");
      out.write("		</nav>\r\n");
      out.write("		<section class=\"carouselSection\">\r\n");
      out.write("			");
      out.write("    <div class=\"carousel\">\r\n");
      out.write("      <div id=\"slide_show\">\r\n");
      out.write("        <a href=\"#\"\r\n");
      out.write("          ><img src=\"");
      out.print(request.getContextPath());
      out.write("/home/media/slide-1.jpg\" alt=\"\" class=\"slide\" id=\"p1\"\r\n");
      out.write("        /></a>\r\n");
      out.write("        <a href=\"#\"\r\n");
      out.write("          ><img src=\"");
      out.print(request.getContextPath());
      out.write("/home/media/slide-2.jpg\" alt=\"\" class=\"slide\" id=\"p2\"\r\n");
      out.write("        /></a>\r\n");
      out.write("        <a href=\"#\"\r\n");
      out.write("          ><img src=\"");
      out.print(request.getContextPath());
      out.write("/home/media/slide-3.jpg\" alt=\"\" class=\"slide\" id=\"p3\"\r\n");
      out.write("        /></a>\r\n");
      out.write("        <a href=\"#\"\r\n");
      out.write("          ><img src=\"");
      out.print(request.getContextPath());
      out.write("/home/media/slide-4.jpg\" alt=\"\" class=\"slide\" id=\"p4\" />\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <i class=\"fa-solid fa-circle-chevron-left\" id=\"navgateleft\"></i>\r\n");
      out.write("      <i class=\"fa-solid fa-circle-chevron-right\" id=\"navgateright\"></i>\r\n");
      out.write("      <div id=\"indicator\">\r\n");
      out.write("        <a href=\"#\" class=\"active\">\r\n");
      out.write("          <i class=\"fa-solid fa-circle-dot\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\"> <i class=\"fa-solid fa-circle-dot\"></i></a\r\n");
      out.write("        ><a href=\"#\"> <i class=\"fa-solid fa-circle-dot\"></i></a\r\n");
      out.write("        ><a href=\"#\"> <i class=\"fa-solid fa-circle-dot\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/home/js/carousel.js\"></script>\r\n");
      out.write("	  \r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("	</header>\r\n");
      out.write("	<main class=\"mainPage\">\r\n");
      out.write("		<section class=\"sideSection\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<section class=\"noticeSection\">\r\n");
      out.write("    <h3>공지사항</h3>\r\n");
      out.write("    <ul class=\"noticeList\">\r\n");
      out.write("        <!-- 공지사항 데이터를 동적으로 표시 -->\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/noticeDetail.do?id=1\">\r\n");
      out.write("                공지사항 제목 1\r\n");
      out.write("            </a>\r\n");
      out.write("            <span class=\"date\">2024-12-19</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/noticeDetail.do?id=2\">\r\n");
      out.write("                공지사항 제목 2\r\n");
      out.write("            </a>\r\n");
      out.write("            <span class=\"date\">2024-12-18</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/noticeDetail.do?id=3\">\r\n");
      out.write("                공지사항 제목 3\r\n");
      out.write("            </a>\r\n");
      out.write("            <span class=\"date\">2024-12-17</span>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/noticeList.do\" class=\"moreButton\">더보기</a>\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"recentProductSection\">\r\n");
      out.write("    <h3>최근 본 상품</h3>\r\n");
      out.write("    <ul class=\"recentProductList\">\r\n");
      out.write("        <!-- 최근 본 상품 데이터를 동적으로 표시 -->\r\n");
      out.write("        <li>\r\n");
      out.write("            <span class=\"name\">상품 1</span>\r\n");
      out.write("            <span class=\"price\">10,000원</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <span class=\"name\">상품 2</span>\r\n");
      out.write("            <span class=\"price\">20,000원</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <span class=\"name\">상품 3</span>\r\n");
      out.write("            <span class=\"price\">30,000원</span>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath());
      out.write("/noticeList.do\" class=\"moreButton\">더보기</a>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("		<section class=\"mainSection\">\r\n");
      out.write("			<!-- 게시판 요약 정보 -->\r\n");
      out.write("			<article class=\"miniBoardSection\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd   HH:mm");
ArrayList<BoardVO> bList = (ArrayList<BoardVO>) request.getAttribute("bList");

      out.write("\r\n");
      out.write("<article class=\"boardArticle\">\r\n");
      out.write("	<h3>게시판 요약</h3>\r\n");
      out.write("	<table>\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>번호</th>\r\n");
      out.write("				<th>제목</th>\r\n");
      out.write("				<th>작성일자</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");
      out.write("	 		");

			int count = 0;
			for (BoardVO data : bList) {
				count++;
			
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"tbNum\">");
      out.print(count);
      out.write("</td>\r\n");
      out.write("				<td class=\"tbMain\"><a\r\n");
      out.write("					href=\" ");
      out.print(request.getContextPath());
      out.write("/boardListSelect.do?no=");
      out.print(data.getNo());
      out.write("&count=1\">");
      out.print(data.getTitle());
      out.write("</a></td>\r\n");
      out.write("				<td class=\"tbDate\">");
      out.print(sf.format(data.getSubdate()));
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

			}
			
      out.write(" \r\n");
      out.write("\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("	<a href=\"");
      out.print(request.getContextPath());
      out.write("/boardSelect.do\"\r\n");
      out.write("		class=\"moreButton\">더보기</a>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</article>\r\n");
      out.write("			<!-- 상품 요약 정보 -->\r\n");
      out.write("			<article class=\"miniShoppingSection\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("<section class=\"productArticle\">\r\n");
      out.write("    <h3>상품 요약</h3>\r\n");
      out.write("    <div class=\"productGrid\">\r\n");
      out.write("        <!-- 상품 1 -->\r\n");
      out.write("        <div class=\"productItem\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/product1.jpg\" alt=\"상품 1 이미지\">\r\n");
      out.write("            <div class=\"price\">10,000원</div>\r\n");
      out.write("            <div class=\"name\">상품 1</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 상품 2 -->\r\n");
      out.write("        <div class=\"productItem\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/product2.jpg\" alt=\"상품 2 이미지\">\r\n");
      out.write("            <div class=\"price\">20,000원</div>\r\n");
      out.write("            <div class=\"name\">상품 2</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 상품 3 -->\r\n");
      out.write("        <div class=\"productItem\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/product3.jpg\" alt=\"상품 3 이미지\">\r\n");
      out.write("            <div class=\"price\">30,000원</div>\r\n");
      out.write("            <div class=\"name\">상품 3</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 상품 4 -->\r\n");
      out.write("        <div class=\"productItem\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/product4.jpg\" alt=\"상품 4 이미지\">\r\n");
      out.write("            <div class=\"price\">40,000원</div>\r\n");
      out.write("            <div class=\"name\">상품 4</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/productList.do\" class=\"moreButton\">더보기</a>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</article>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section class=\"loginSection\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

CustomerVO cvo = MyUtility.returnCvoBySession(session);
Cookie[] ckList= request.getCookies();
String cid = null;
    for (Cookie cookie : ckList) {
        // 원하는 쿠키 이름 확인
        if (cookie.getName().equals("id")) {  
             cid= cookie.getValue();  // 쿠키 값 가져오기
        }
    }

      out.write("\r\n");
      out.write("\r\n");

if (cvo == null) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<article class=\"loginInput\">\r\n");
      out.write("	<form method=\"post\" action=\"/jspHomePage/customerLoginCheck.do\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><input type=\"text\" name=\"id\" id=\"id\"\r\n");
      out.write("				placeholder=\" 아이디 또는 전화번호\" ");
      out.print((!MyUtility.isNullOrEmpty(cid))?"value="+cid:"" );
      out.write("></li>\r\n");
      out.write("			<li><input type=\"password\" name=\"pwd\" id=\"psw\"\r\n");
      out.write("				placeholder=\" 비밀번호\" /></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<!-- 상태유지 -->\r\n");
      out.write("		<div class=\"maint\">\r\n");
      out.write("			<input type=\"checkbox\" name=\"maint\" class=\"maint\" ");
      out.print((!MyUtility.isNullOrEmpty(cid))?"checked":"" );
      out.write("> <label\r\n");
      out.write("				for=\"maint\" >아이디 저장</label>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 로그인 버튼 -->\r\n");
      out.write("		<button type=\"submit\">로그인</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"loginNav\">\r\n");
      out.write("	<ul style=\"display: flex\">\r\n");
      out.write("		<li><a href=\"#\">비밀번호 찾기</a></li>\r\n");
      out.write("		<li><a href=\"#\">아이디 찾기</a></li>\r\n");
      out.write("		<li><a href=\"/jspHomePage/home/customerRegistPage.jsp\">회원가입</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

} else {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 성공 화면 -->\r\n");
      out.write("<table class=\"afterLoginPage\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"300\" align=\"center\">");
      out.print(cvo.getName());
      out.write(" 님 로그인 되었습니다.</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<nav class=\"loginNav\">\r\n");
      out.write("	<ul style=\"display: flex\">\r\n");
      out.write("		<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myPageAlert.do\">마이페이지</a></li>\r\n");
      out.write("		<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/customerLogout.do\">로그아웃</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("	</main>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<footer>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("      <article>\r\n");
      out.write("        <div><a href=\"#\">로그인 | </a><a href=\"#\">전체서비스 | </a><a href=\"#\">서비스안내 | </a><a href=\"#\">오류신고 | </a><a href=\"#\">고객센터 | </a></div>\r\n");
      out.write("        <div>직접 콘텐츠를 편집합니다.</div>\r\n");
      out.write("        <div>이 콘텐츠의 저작권은 저작권자 또는 제공처에 있으며, 이를 무단 이용하는 경우 저작권법 등에 따라 법적 책임을 질 수 있습니다.</div>\r\n");
      out.write("      </article>");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
